
Event.find_or_create_by_name_and_priority('Before the bushfire season', 10)
Event.find_or_create_by_name_and_priority('During the bushfire season', 20)
Event.find_or_create_by_name_and_priority('Night before you evacuate/defend', 30)

event = Event.find_by_name('Before the bushfire season')
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Clear fine fuels around the house/property - weeds, leaf litter, dead branches (smaller than diameter of a pencil).', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Trim tree branches overhanging the house.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Trim shrubs around the house - no shrubs over 1 metre.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Clear gutters.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Cover air vents with fine metal mesh.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Check hose fittings are in good working order.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Check hoses reach entire house.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Prepare emergency stay/go kit.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Place emergency stay/go kit in an easy accessible location.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Move firewood away from the house.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Move any flammable items away from the house.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Back up computer files onto external hard drive.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Know where metal buckets, mops, rakes, etc are located.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Prepare relocation kit.', event.id)

event = Event.find_by_name('During the bushfire season')
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Fill external water sources - eg. wheelie bins with lids.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Maintain fine fuels around the house.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Keep gutters clear.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Know where metal buckets, mops, rakes, etc are located.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Know where boots are for all household members.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Practice moving through the house in full protective gear in the complete dark.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Find somewhere safe to put photos, scrapbooks, documents (birth certificates, insurance docs & receipts, passports).', event.id)

event = Event.find_by_name('Night before you evacuate/defend')
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Listen to ABC 774 for updates on fire conditions.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Check warrandyte.org.au Real Time Info page regularly for updates on fire & weather conditions.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Charge mobile phones and i-pods.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Check emergency stay/go kit is complete.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Move door mats and other loose flammable items inside or away from the house.', event.id)
Task.find_or_create_by_custom_and_name_and_event_id(false, 'Put emergency stay/go kit in car or near the front door.', event.id)
